multiscales: [13, 26, 52]
anchorbox: [
                [(0.28, 0.22), (0.38, 0.48), (0.9, 0.78)],
                [(0.07, 0.15), (0.15, 0.11), (0.14, 0.29)],
                [(0.02, 0.03), (0.04, 0.07), (0.08, 0.06)],
            ]
num_classes: 13
img_size: 416

confidence_threshold: 0.5
iou_threshold : 0.8
ignore_iou_thresh : 0.5